name: Docker Image CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shinde11/india-covid:frontend
